# Generated by Django 4.1.7 on 2023-08-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRBookingSystemApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('guests', models.IntegerField()),
                ('category', models.CharField(default='', max_length=100)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('sqft', models.IntegerField()),
                ('desc', models.CharField(max_length=500)),
                ('Price', models.IntegerField()),
                ('Hotel_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/images')),
            ],
        ),
    ]
