# Generated by Django 4.1.7 on 2023-08-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRBookingSystemApp', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_name',
            new_name='booker_name',
        ),
    ]
