# Generated by Django 4.1.7 on 2023-08-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRBookingSystemApp', '0007_rename_profile_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='user',
        ),
    ]
